author: 若离QQ：2909998156
# 推送方式：0：邮件推送；1：qmsg推送；2：pushplus推送
sendType: 0
# 当且仅当sendType为0时有用，邮箱API的地址
emailApiUrl: 'https://api.ruoli.cc/mail/sendMail'
# 当且仅当sendType为1时有用，qmsg的Key（如需使用请自行更改）
myQmsgKey: ''
# submitForm提交数据进行加密的api接口
encryptApi: 'https://api.ruoli.cc/wise/v3/encrypt'


#用户组配置
##################################################
# 温馨提示：请仔细注意每个模板是属于哪个任务类型的配置！##
##################################################
users:
  # 第二个用户配置
  # 以下配置为信息收集
  # 这里默认仅适配宜宾学院，其他学校自行修改
  - user:
        # 任务类型（收集：0、签到：1、查寝2）
        type: 0
        # 学校名称
        schoolName: '北华大学'
        # 账号
        username: '201817040124'
        # 密码
        password: 'WYLwyl123456'
        # 定位位置信息
        address: '吉林省长春市二道区'
        #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
        sendKey: '1312800827'
        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
        # 经纬度信息
        lon: 125.381508
        #经纬度信息
        lat: 43.889298
        # 是否检查表单的标题（1代表检查，0代表不检查）
        checkTitle: 1
        # 代理ip信息（若无可忽略本设置、该配置仅供您所在环境ip被ban且自己拥有代理ip使用）（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
        proxy: ''
        # isOffset 坐标偏移开关，默认打开坐标偏移开关，若一直出现不在签到范围且确保自己填写的lon和lat在坐标范围内，请尝试关闭本功能
        isOffset: true
        # 表单信息
        forms:
            - form:
                  title: 你早间的体温是否正常：
                  value: 正常
            - form:
                  title: 你午间的体温是否正常：
                  value: 正常
            - form:
                  title: 你晚间的体温是否正常：
                  value: 正常
            - form:
                  title: 4、你今日是否有不适症状：
                  value: 无不适症状
            - form:
                  title: 你当前的状态
                  value: 正常
